### ISSUE TITLE
Subscriber IP whitelisting

### ISSUE THREAD

**Issue by jdswinbank** [jdswinbank/Comet#10]
This could be implemented as for publishers (see #2), but is lower priority.

**Comment by thusser** [comment]
We'd really like to see this feature in Comet, because for a very specific case we need a broker that only a very small number of clients can connect to. If you don't mind, I'd probably have a look at that issue sometime next week, try to create a patch and make a pull request for that.

**Comment by jdswinbank** [comment]
I'd be delighted to receive a PR for this feature. Thanks in advance!

**Comment by jdswinbank** [comment]
Done in #41.
