### ISSUE TITLE
'+' symbol in IVORN fragment?

### ISSUE THREAD

**Issue by timstaley** [jdswinbank/Comet#37]
Hi John,

quick question on a technicality:
currently IVORNS are given the yay/nay by this regex:
https://github.com/jdswinbank/Comet/blob/62318be9e6d55aadddd579e1c3c40f2035e58d04/comet/utility/voevent.py#L20

Should the set of fragment characters include '+', or is there a good reason for exclusion?

Seems to be valid for HTTP, cf http://stackoverflow.com/a/1547940/725650, AFAICT, and it is occasionally useful when assigning substream IDs, e.g. if referring to some event generally known via its co-ordinates.

**Comment by timstaley** [comment]
Ok, the branch referenced above is the naive solution. Seems to work in practice but I'm guessing you may want to unit-test it.

**Comment by jdswinbank** [comment]
Thanks Tim -- I expect to be pretty much snowed under today, but I'll get to this as soon as I have a chance!

**Comment by jdswinbank** [comment]
I find the [relevant IVOA recommendation](http://www.ivoa.net/documents/REC/Identifiers/Identifiers-20070302.html#components) pretty inscrutable here, unfortunately. After giving it a hard stare, I think I agree with you that this should be ok, and have implemented it in 9337eab51eaa. Could you confirm that that does what you want, please?

**Comment by timstaley** [comment]
Works great - many thanks!

**Comment by jdswinbank** [comment]
Thanks Tim. Have you tried the rest of the master branch? I'm going to push out a new Comet release with this included shortly, and any reports of success or failure would be of interest.

**Comment by timstaley** [comment]
Yes, I simply checked out the current master. All looks OK, have tested both comet-send and the usual 'listen and run handler' functionality.
