### ISSUE TITLE
Cannot install on Python 3, needs py2-ipaddress

### ISSUE THREAD

**Issue by guillochon** [jdswinbank/Comet#44]
Hi all, I see that Comet is supposed to have experimental Python 3.x support, but I'm running into issues installing the py2-ipaddress library in Python 3, which appears to be required:

```
Collecting py2-ipaddress
  Using cached py2-ipaddress-3.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    py2-ipaddress: For Python 3.x, please use the official ipaddress module.
```

Is there a workaround? Thanks!

**Comment by jdswinbank** [comment]
The experimental Python 3 support is only available on the master branch: it hasn't yet been released to PyPI. The following should work:

```
$ pyvenv-3.5 cmt
$ . cmt/bin/activate
$ git clone https://github.com/jdswinbank/Comet.git
$ cd Comet/
$ pip install -r requirements3.txt
$ python setup.py install
```

Please let me know if you run into problems: I'd like a few more reports of how well this code works in practice before I make a release.
