### ISSUE TITLE
Conda package for Comet

### ISSUE THREAD

**Issue by duncanmmacleod** [jdswinbank/Comet#57]
Hi @jdswinbank. I'm interested in distributing `Comet` with [Conda](https://conda.io) via [conda-forge](https://conda-forge.org).

Do you have any objections to me doing this?
Do you wish to be named as a maintainer?

Thanks
Duncan

**Comment by jdswinbank** [comment]
Hi Duncan — no objection from me. I'm afraid I don't know much about Conda, though — does this require anything to be added to the Comet repository, or is it purely something you can do within conda-forge? If the latter, I don't think there's any need to add me as a maintainer.

**Comment by duncanmmacleod** [comment]
This is entirely external to the Comet repo, so I'll leave your name off. It can always be added again later if you want to get more involved.

Thanks, I'll point you at the recipe once its completed.

**Comment by jdswinbank** [comment]
Sounds great — thanks for doing this.

**Comment by duncanmmacleod** [comment]
@jdswinbank, it turns out there's already a conda package called `comet`, so I will have to rename the Conda package for this code. Can you just let me know if there's an alternative name you would like, or whether you prefer one of

- `pycomet`
- `python-comet`

?

**Comment by duncanmmacleod** [comment]
Actually, nevermind, the other package has been renamed to make space.
