### ISSUE TITLE
More flexible plugin installation location

### ISSUE THREAD

**Issue by jdswinbank** [jdswinbank/Comet#62]
Dumping plugins into `Comet/comet/plugins` isn't convenient, especially if you're (e.g.) installing Comet using pip into a Docker container. Please come up with a flexible way of enabling the user to specify the plugin location.

**Comment by jdswinbank** [comment]
One nice possibility might be a namespace package, although, more work is necessary to see if it can actually be made to work.

**Comment by JulienPeloton** [comment]
Hi John,

#63 introduced the `COMET_PLUGINPATH` environment variable to deal with plugins in a easier way from an user point of view. The published documentation does not mention it yet, so should I consider it as still experimental?

In any case, I'm planning to write plugins so I can report on its use if it is useful.

**Comment by jdswinbank** [comment]
Hi @JulienPeloton —

This feature hasn't yet made it into a released version of Comet, so from that point of view it is still experimental. However, it is available (and [documented](https://comet.transientskp.org/en/latest/handlers.html)) on the `master` branch, if you are willing to try running that.

As far as I'm aware, `master` is reasonably stable: I intend to release it as Comet 4.0.0 when I get chance (although that might not be for a while yet). However, be warned that it does include a substantial overhaul of the command line interface — see the [release notes](https://comet.transientskp.org/en/latest/history.html#development-version) for details.

**Comment by jdswinbank** [comment]
I think this issue was closed by #63

**Comment by JulienPeloton** [comment]
Thanks @jdswinbank for the clarification and the pointer to the release notes!
