### ISSUE TITLE
Can’t connect to the server at comet.transientskp.org

### ISSUE THREAD

**Issue by JulienPeloton** [jdswinbank/Comet#64]
Hi John,

Thanks for this work. It seems that the documentation website (http://comet.transientskp.org/) cannot be reached. Has it changed location or servers are momentarily down?

**Comment by jdswinbank** [comment]
Hi @JulienPeloton — thanks for the heads up. Should be working now; please let me know if you spot any other problems.

**Comment by JulienPeloton** [comment]
Thanks @jdswinbank, it is working like a charm!
